# api/config/packages/api_platform.yaml
api_platform:
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    keep_legacy_inflector: false
    use_symfony_listeners: true
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']


